# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hag.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thag.proto\x12\x03hag\"\x1f\n\x0eSendOtpRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"@\n\x0fSendOtpResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03otp\x18\x03 \x01(\t\"/\n\x10VerifyOtpRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"5\n\x11VerifyOtpResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\rHagOtpService\x12\x34\n\x07SendOtp\x12\x13.hag.SendOtpRequest\x1a\x14.hag.SendOtpResponse\x12:\n\tVerifyOtp\x12\x15.hag.VerifyOtpRequest\x1a\x16.hag.VerifyOtpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDOTPREQUEST']._serialized_start=18
  _globals['_SENDOTPREQUEST']._serialized_end=49
  _globals['_SENDOTPRESPONSE']._serialized_start=51
  _globals['_SENDOTPRESPONSE']._serialized_end=115
  _globals['_VERIFYOTPREQUEST']._serialized_start=117
  _globals['_VERIFYOTPREQUEST']._serialized_end=164
  _globals['_VERIFYOTPRESPONSE']._serialized_start=166
  _globals['_VERIFYOTPRESPONSE']._serialized_end=219
  _globals['_HAGOTPSERVICE']._serialized_start=222
  _globals['_HAGOTPSERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
